name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Cache Gradle files
      uses: actions/cache@v2
      with:
        path: ~/.gradle/cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        android-version: 29
        
    - name: Build ARM7 APK
      run: ./gradlew assembleDebug -PcpuArchitecture=armeabi-v7a
      
    - name: Build ARM64-V8A APK
      run: ./gradlew assembleDebug -PcpuArchitecture=arm64-v8a
      
    - name: Upload ARM7 APK
      uses: actions/upload-artifact@v2
      with:
        name: app-arm7
        path: app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
        
    - name: Upload ARM64-V8A APK
      uses: actions/upload-artifact@v2
      with:
        name: app-arm64-v8a
        path: app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
